name: vscode
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

grade: stable
confinement: classic

parts:
  vscode:
    plugin: dump
    source: https://go.microsoft.com/fwlink/?LinkID=760868
    source-type: deb
    override-build: |
      DEB_API="https://go.microsoft.com/fwlink/?LinkID=760868"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'_' -f2)
      echo $VERSION > $SNAPCRAFT_STAGE/version

      # Correct path to icon.
      sed -i 's|Icon=code|Icon=/usr/share/pixmaps/code\.png|g' usr/share/applications/code.desktop
      snapcraftctl build
    build-packages:
      # Visual Studio Code is only publishes debs for amd64,
      # so fail the build on other architectures.
      - on amd64:
        - curl
        - sed
      - else fail
    stage-packages:
      - libasound2
      - libgconf2-4
      - libgtk2.0-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
  electron-launch:
    plugin: dump
    source: files/

apps:
  vscode:
    command: bin/electron-launch ${SNAP}/usr/share/code/bin/code
    desktop: usr/share/applications/code.desktop
